# Generated by Django 5.2.1 on 2025-06-03 08:41

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDiscoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', django_jalali.db.models.jDateField()),
                ('end_day', django_jalali.db.models.jDateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending_1', 'منتظر تایید سرپرست'), ('approved_1', 'تایید توسط سرپرست'), ('rejected_1', 'رد توسط سرپرست'), ('pending_2', 'منتظر تایید مدیر بخش'), ('approved_2', 'تایید توسط مدیر بخش'), ('rejected_2', 'رد توسط مدیر بخش'), ('pending_3', 'منتظر تایید مدیر منابع انسانی'), ('approved_3', 'تایید توسط مدیر منابع انسانی'), ('rejected_3', 'رد توسط مدیر منابع انسانی'), ('pending_4', 'منتظر تایید مدیر'), ('approved_4', 'تایید نهایی'), ('rejected_4', 'رد نهایی')], default='pending_1', max_length=20)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30, verbose_name='روز')),
                ('description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
